
import { GoogleGenAI, Type, Schema } from "@google/genai";
import { GeneratedBuildingData, Building, Tier } from "../types";

// Safety check for API key
const apiKey = process.env.API_KEY || '';
const ai = new GoogleGenAI({ apiKey });

export const generateNextBuilding = async (
  currentTheme: string,
  resourceName: string,
  tier: Tier,
  existingBuildings: Building[],
  totalGenerated: number
): Promise<GeneratedBuildingData> => {
  if (!apiKey) {
    throw new Error("API Key missing");
  }

  const lastBuilding = existingBuildings[existingBuildings.length - 1];
  const targetCost = Math.floor(lastBuilding.baseCost * 8); 
  const targetProd = Math.floor(lastBuilding.baseProduction * 5);

  let tierContext = "";
  switch(tier) {
    case Tier.QUANTUM:
      tierContext = "Focus on subatomic particles, waves, and fundamental forces. Very scientific and abstract.";
      break;
    case Tier.MACROCOSM:
      tierContext = "Focus on planetary scale, industrial machinery, ecology, or civilization building.";
      break;
    case Tier.COSMIC:
      tierContext = "Focus on stars, black holes, galactic mega-structures, and dyson spheres.";
      break;
    case Tier.MULTIVERSAL:
      tierContext = "Focus on dimension hopping, reality bending, time travel, and god-like constructs.";
      break;
    case Tier.OMNIPOTENT:
      tierContext = "Focus on ruling the galaxy, absolute power, divine intervention, and rewriting the laws of physics.";
      break;
  }

  const prompt = `
    I am an idle game engine.
    Current Theme: ${currentTheme}.
    Current Evolution Tier: ${tier}.
    Resource: ${resourceName}.
    
    Context for this tier: ${tierContext}

    The last building was "${lastBuilding.name}" (Cost: ${lastBuilding.baseCost}, Prod: ${lastBuilding.baseProduction}).
    
    Generate a NEW, UNIQUE building that is more advanced.
    It should have a flavor fitting the '${tier}' tier.
    Target Base Cost around: ${targetCost}.
    Target Base Production around: ${targetProd}.
  `;

  const schema: Schema = {
    type: Type.OBJECT,
    properties: {
      name: { type: Type.STRING, description: "Creative name of the building" },
      description: { type: Type.STRING, description: "Short functional description" },
      flavorText: { type: Type.STRING, description: "Funny or lore-heavy flavor text" },
      baseCost: { type: Type.NUMBER, description: "Cost to buy the first one" },
      baseProduction: { type: Type.NUMBER, description: "Resource generated per second" },
    },
    required: ["name", "description", "flavorText", "baseCost", "baseProduction"],
  };

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: schema,
        temperature: 1.1, // High creativity
      },
    });

    const text = response.text;
    if (!text) throw new Error("No response from AI");
    
    const data = JSON.parse(text) as GeneratedBuildingData;
    
    // Fallback sanity checks
    if (!data.name) data.name = "Unknown Artifact";
    if (data.baseCost < lastBuilding.baseCost) data.baseCost = targetCost;
    
    return data;
  } catch (error) {
    console.error("Gemini generation failed:", error);
    // Fallback if AI fails
    return {
      name: `Procedural Fabricator Mk.${existingBuildings.length + 1}`,
      description: "An anomalous structure generated by fallback protocols.",
      flavorText: "The AI was sleeping, so you got this generic box.",
      baseCost: targetCost,
      baseProduction: targetProd
    };
  }
};

export const generateStoryEvent = async (
  theme: string,
  resourceName: string,
  tier: Tier,
  totalGenerated: number
): Promise<string> => {
    if (!apiKey) return "The universe expands silently.";

    const prompt = `
      Write a single sentence cryptic or awe-inspiring log entry for an idle game.
      Theme: ${theme}.
      Tier: ${tier}.
      Resource: ${resourceName}.
      Total Generated so far: ${totalGenerated}.
      Make it feel like progress is being made towards a grand mystery.
    `;

    try {
      const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: prompt,
        config: {
           maxOutputTokens: 50,
           temperature: 0.9
        }
      });
      return response.text?.trim() || "Energy surges through the conduit.";
    } catch (e) {
      return "Static fills the void.";
    }
};

export const generatePrestigeTheme = async (): Promise<{theme: string, resource: string}> => {
  if (!apiKey) return { theme: "Digital Void", resource: "Bits" };
  
  const schema: Schema = {
    type: Type.OBJECT,
    properties: {
      theme: { type: Type.STRING },
      resource: { type: Type.STRING }
    },
    required: ["theme", "resource"]
  };

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: "Generate a new, creative, abstract theme for a universe simulation (e.g., 'The Cotton Candy Dimension', 'Clockwork Hell', 'Neon Cyberverse'). Also name the primary resource (e.g. 'Sugar', 'Gears', 'Data').",
      config: {
        responseMimeType: "application/json",
        responseSchema: schema
      }
    });
     const data = JSON.parse(response.text || "{}");
     return {
       theme: data.theme || "New Universe",
       resource: data.resource || "Matter"
     };
  } catch (e) {
    return { theme: "Parallel Dimension", resource: "Antimatter" };
  }
}
